version: '3'

services:
  consul:
    image: consul:1.15.4
    container_name: consul
    ports:
      - "8500:8500"  # Web UI
      - "8600:8600"  # DNS
    environment:
      - CONSUL_BIND_INTERFACE=eth0
    networks:
      - consul_network
    restart: unless-stopped
networks:
  consul_network:
    driver: bridge
